# Generated by Django 5.0.1 on 2024-03-15 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('num_warehouses', models.IntegerField()),
                ('revenue_growth_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('average_revenue_per_product', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('registration_number', models.IntegerField()),
                ('walked', models.IntegerField()),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.company')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.account')),
                ('notification_detail_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.notification_detail')),
            ],
        ),
        migrations.AddField(
            model_name='notification_detail',
            name='notification_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.notification_type'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.IntegerField()),
                ('quantity_warning_limit', models.IntegerField()),
                ('intelligant_repelnishement', models.IntegerField()),
                ('forcast_demand', models.IntegerField()),
                ('is_shipment', models.BooleanField(default=False)),
                ('product_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.product_type')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('permissions', models.ManyToManyField(related_name='roles_where_permission_belong', to='API_DATABASE_REQUESTS.permission')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.role'),
        ),
        migrations.CreateModel(
            name='Shippment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_departing_time', models.DateTimeField()),
                ('scheduled_arriving_time', models.DateTimeField()),
                ('is_departed', models.BooleanField(default=False)),
                ('is_arrived', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('car_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.car')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.company')),
                ('driver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.account')),
            ],
        ),
        migrations.AddField(
            model_name='notification_detail',
            name='shippment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.shippment'),
        ),
        migrations.CreateModel(
            name='Shippment_Product_OnetoMany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.product')),
                ('shippment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.shippment')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('num_products', models.IntegerField()),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.company')),
            ],
        ),
        migrations.AddField(
            model_name='shippment',
            name='arriving_warehouse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coming_shippments', to='API_DATABASE_REQUESTS.warehouse'),
        ),
        migrations.AddField(
            model_name='shippment',
            name='departing_warehouse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gone_shippments', to='API_DATABASE_REQUESTS.warehouse'),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=100)),
                ('sales_type', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('date', models.DateField()),
                ('revenue', models.IntegerField()),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.company')),
                ('warehouse_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Product_archieve',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_sold', models.IntegerField()),
                ('product_archieve_type', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('entity_type', models.CharField(max_length=100)),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.company')),
                ('product_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.product_type')),
                ('warehouse_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.warehouse'),
        ),
        migrations.AddField(
            model_name='notification_detail',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.warehouse'),
        ),
        migrations.AddField(
            model_name='account',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.warehouse'),
        ),
    ]
