# Generated by Django 5.0.1 on 2024-03-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_DATABASE_REQUESTS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
