# Generated by Django 5.0.1 on 2024-03-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_DATABASE_REQUESTS', '0002_warehouse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='num_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='num_warehouses',
            field=models.IntegerField(default=0),
        ),
    ]
