# Generated by Django 5.0.1 on 2024-03-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_DATABASE_REQUESTS', '0004_alter_company_revenue_growth_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='latitude',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='longitude',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
