# Generated by Django 5.0.1 on 2024-03-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_DATABASE_REQUESTS', '0005_alter_warehouse_latitude_alter_warehouse_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='num_products',
            field=models.IntegerField(default=0),
        ),
    ]
