# Generated by Django 5.0.1 on 2024-03-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_DATABASE_REQUESTS', '0007_rename_model_car_name_alter_car_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='walked',
            field=models.IntegerField(default=0),
        ),
    ]
