# Generated by Django 5.0.1 on 2024-03-27 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_DATABASE_REQUESTS', '0008_alter_car_walked'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_DATABASE_REQUESTS.company'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='average_revenue_per_product',
            field=models.IntegerField(default=0),
        ),
    ]
