# Generated by Django 5.0.1 on 2024-03-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_DATABASE_REQUESTS', '0010_alter_product_forcast_demand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
